#!/bin/bash
# Date: 10-06-2013
# Author: "lapipaplena" <lapipaplena@gmail.com>
# Version: 9.0
# Licence: GPL v3.0
# Description: Script de desarrollo del tractatus
# Require: cowsay ccze wget
####
DIR=$HOME/destrac
## comprobar privilegios
if [ "$(id -u)" = "0" ]
then 
	echo
	echo "<< Ejecutar el script como usuario sin privilegios... abortando.... >>" 
	echo
	exit 1
fi
function fcolor ()
{
	echo $1 | ccze -A
}
function fdir ()
{
	if [ -d $DIR ]
	then
		rm -R $DIR/*
	else
		mkdir $DIR
	fi
	cd $DIR
}
function fdesglosetractatus ()
{
	if [ -s files ]
	then
		echo
	else
		mkdir files
	fi
	cd files
	## <bloque de miguelgf de linuxespanol.com>
	cat ../0-file1.txt | awk 'BEGIN {ESTADO=1} \
	{ \
			if (ESTADO == 1 && NF == 0) \
					{ESTADO=1} \
			else    {       if (ESTADO==1 && NF != 0) {NOMBRE=$1; ESTADO=2; print $0 >> NOMBRE} \
							else    {       if (ESTADO==2 && NF == 0) {ESTADO=1} \
											else { print $0 >> NOMBRE } \
									} \
					} \
	}'
    ## </bloque>
	echo
	fcolor "... proceso terminado...."
	cd ..
	ls files > 0-lista.txt
	if [ ! -s 0-lista.txt ]
	then
		color "Se han detectado errores al procesar la descarga del Tractatus"
		exit
	else
		echo
		fcolor  "<< Creado el directorio "files" correctamente ... >>"
	fi
}
function fdescarrega ()
{
	echo
	fcolor " [1] Descargar última versión del Tractatus via wget"
	fcolor " [2] Descargar última versión del Tractatus via Dropbox"
	fcolor " [3] Trabajar con una copia existente"
	echo
	read -p "<< Ingresar una opción: >> " OPC
	echo
	case $OPC in
	1)
		fdir
		curl -o 1-tractatus.txt http://crontux.homelinux.com/1-tractatus.txt
		cat 1-tractatus.txt | sed '1d' > 0-file1.txt
		fdesglosetractatus
		echo;;
	2)
		fdir
		cat $HOME/Dropbox/Dades/tractatus/1-tractatus.txt | sed '1d' > 0-file1.txt
		fdesglosetractatus
		echo;;
	3)
		if [ -d $DIR/files ]
		then
			cd $DIR/files
		else
			if [ -d $DIR ]
			then
				rm -R $DIR
			fi
			echo
			fcolor "<< No se han encontrado datos del tractatus.  >>"
			echo
			read -p "<< ¿Desea descargar el tractatus? >> (s/n) " OPC2
			echo
			if [ $OPC2 = s ]
			then
				fdescarrega
			else
				exit 1
			fi
		fi
		echo;;
	esac
}
function fpagina_man ()
{
	MAN=$(man $COMANDO | wc -l 2>/dev/null)
	if [ $MAN -gt 2 ]
	then
		echo
		read -p "No existe la entrada $COMANDO en el tractatus... ¿Visualizar su página man?  (s/n) " CON
		echo
		if [ $CON = s ]
		then
			echo
			man $COMANDO
			echo
		else
			echo
		fi
	else
		cowsay -f tux "Concepto inexistente en el tractatus y en las páginas man"
	fi
	read
}
##### INICI PROGRAMA #####
fdescarrega
cd $DIR/files
NUM2=$(cat ../0-file1.txt | awk 'BEGIN { FS="\n"; RS="" } {print $1 }' | awk -F " " '{print$1 }' | wc -l)
while [ "$OPC1" != 3 ]
do
	echo
	fcolor "[1] Entrar una busqueda"
	fcolor "[2] Realizar busqueda avanzada"
	fcolor "[3] Salir"
	echo
	read -p "<< Ingresar opción (NO distingue mayúsculas y minúsculas): >> " OPC1
	echo
	case $OPC1 in
	1)
		# Buscar los comandos deseados.
		echo
			fcolor "<< Introducir dato a consultar: >>"
			echo
			read COMAND_
			COMANDO=$(echo "$COMAND_" | tr 'A-Z' 'a-z')
			clear
		if [ -e "$COMANDO" ]
		then
			pr -f -d -h $COMANDO $COMANDO | ccze -A
			echo
			read
		else
			fpagina_man
		echo
		fi
#		read
		clear;;
	2)
		### Busqueda recursiva
		clear
		echo
			fcolor "<< Introducir dato a consultar: >>"
			echo
			read COMAND_
			COMANDO=$(echo "$COMAND_" | tr 'A-Z' 'a-z')
			clear
			grep -l $COMANDO * | cut -d/ -f2 > ../0-file3.txt
			if [ -s ../0-file3.txt ]
			then
				OP=s
				while [ $OP = s ]
				do
					echo
					fcolor "El dato entrado sale en los siguientes ficheros: "
					echo
					numero=0
					for linia in `cat ../0-file3.txt`; do
						let numero+=1
						echo "[$numero] $linia"
					done
					echo
					echo "[0] Cancelar"
					echo
					echo
					fcolor "<< Comando a mostrar... >>"
					read COM
					if [ $COM -ne 0 ] && [ $COM -le $numero ];
					then
						comando=`sed -n ${COM}p ../0-file3.txt`
						if [ "$?" -eq "0" ]
						then
							echo
							clear
							pr -f -d -h $comando $comando | ccze -A
						else
							echo
						fi
						read
						echo
						fcolor "<< Consultar otro comando del listado? [s/n] >>"
						read OP
						clear
					elif [ $COM -gt $numero ] ;
					then
						echo
						clear
						cowsay -f tux "No existe en el listado"
						read
					else
						OP="n"
						clear
					fi
				done
			else
				fpagina_man
				echo
			fi
		echo;;
	3);;
	esac
done
clear
echo
echo  "============================================================="
fcolor "<< La base de datos del tractatus cuenta con $NUM2 entradas >>"
echo  "============================================================="
cd $HOME
echo
exit